#!/usr/bin/expect -f
set timeout -1
spawn ./compile2
expect "input file name:"
send -- "cht2dfluid.box\r"
expect "Input old (source) file name:"
send -- "box\r"
expect "Input new (output) file name:"
send -- "cht2d\r"
expect "Input .rea / .re2 name:"
send -- "cht2d\r"
expect "Input mesh tolerance (default 0.2):"
send -- "\r"
expect eof
